### ISSUE TITLE
Problems logging into quay.io

### ISSUE THREAD

**Issue by ddl-pjohnson** [app-registry/quay-helmv3-plugin#6]
While attempting to log in to quay.io, I'm getting the following error:
```
++ helm quay login quay.io/domino -u XXXXX -p XXXXX
usage: appr [-h]
            {pull,run-server,show,inspect,list,delete-package,helm,version,logout,deploy,plugins,push,login,config,channel,jsonnet}
            ...
appr: error:
message: '404 Client Error: NOT FOUND for url: https://quay.io/cnr/api/v1/users/login'
response: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

  <title>404 Not Found</title>

  <h1>Not Found</h1>

  <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

  '

Error: plugin "quay" exited with error
```

I can't see anything on quay.io's status page or anything about deprecations, was there a change announced?

**Comment by csymeonides-mf** [comment]
Did you ever get this resolved? I'm having the same issue.

**Comment by ddl-pjohnson** [comment]
Changing the plugin commands to use the defaults worked, e.g.:
```helm quay registry login quay.io/mycompany```
becomes:
```helm registry login quay.io/mycompany```

I think this requires a recent version of helm maybe?

**Comment by csymeonides-mf** [comment]
Yes - had to contact Quay support and after a lot of back and forth I discovered that:
* They removed support for Helm 2 charts, only OCI charts are supported now
* They posted this as a banner on their site (allegedly) but didn't bother emailing any customers
* The old chart repos are no longer accessible
* If you want to push new charts under the same chart name, you need to delete the old chart repo and create a new one
* Deleting these old repos is not possible via their web console, you need to use their API:
  * `curl -X DELETE -H "Authorization: Bearer ${ACCESS_TOKEN}" https://quay.io/api/v1/repository/${NAMESPACE}/${CHART_NAME}`
  * See [instructions for generating an access token](https://docs.projectquay.io/api_quay.html#_create_oauth_access_token)
* You can create the new repo in the usual way (same as for a docker image repo)
* When you push a chart, it will read the `name` and `version` fields in your `Chart.yaml` to determine where to push it and how to tag it
* You need a recent version of the helm client (3.8.0 worked for me)
* To login: `helm registry login quay.io/${NAMESPACE}`
* To push: `helm push ${CHART_FILE} oci://quay.io/${NAMESPACE}`
* To pull: `helm pull "oci://quay.io/${NAMESPACE}/${CHART_NAME}" --version=${VERSION}`
